- name: Install Docker CE
  hosts: docker
  become: true
  tasks:
    - name: Update APT and packages
      become: true
      apt:
        update_cache: true
        upgrade: full
        force_apt_get: yes

    - name: Download and install docker key
      block:
        - name: Create apt keyring directory
          file:
            path: "/etc/apt/keyrings"
            state: directory
            owner: root
            group: root
            mode: 0755
          become: true

        - name: Remove old key if exists
          become: true
          file:
            path: "/etc/apt/keyrings/docker-keyring.gpg"
            state: absent

        - name: Download docker key
          become: true
          shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker-keyring.gpg

        - name: install docker repo
          become: true
          copy:
            dest: /etc/apt/sources.list.d/docker.list
            content: |
              deb [arch="amd64" signed-by=/etc/apt/keyrings/docker-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable

    - name: Install dependencies
      apt: "name={{ item }} state=present"
      with_items:
        - apt-transport-https
        - ca-certificates
        - gnupg
        - sudo
        - git
        - curl
        - acl
        - python3-pip

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install docker-py
      pip:
        name: docker-py

    - name: Install docker
      apt: "name={{ item }} state=present"
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
